### ISSUE TITLE
Rename poucave repository to "telescope" and update references to poucave to use the new name

### ISSUE THREAD

**Issue by petemoore** [mozilla-services/poucave#862] opened 2021-08-12 13:06 UTC
Reasons in favor of Telescope:

- easier to pronounce or remember for English speaking crowds
- expression of the metaphor (see what you cannot see with naked eyes :))

Reasons in favor of Poucave:

- original name (no other project)
- means snitch, which reports invisible details to stakeholders
- no need to rename everything (avoid situation with 3 names, poucave, telescope, delivery-checks)

### Update 25/08/2021: (copied from #857)

* Check before renaming on Github:
* https://github.com/mozilla-services/cloudops-infra/tree/master/projects/poucave
* Rename repo https://github.com/mozilla-services/poucave/ 
* Rename cloudops project poucave to delivery-checks (+jenkins?)
* Update documentation everywhere where Poucave is mentioned
 * [Blog post](https://blog.mathieu-leplatre.info/poucave-an-observation-standpoint-for-our-services.html)?

**Comment by jwhitlock** [comment] 2021-08-16 17:52
This could be duplicate of #857, which goes into specifics of renaming.

I have a slight preference for keeping Poucave as the code name, and using Telescope as a product name for the Taskcluster integration. There's a long tradition of code names at Mozilla (Bedrock vs www.mozilla.org, Ichnaea vs Mozilla Location Services). There's already a Poucave / Delivery Checks split for this project.

If we go this route, we'd need to add a sentence or two to the intro, like "Poucave is the engine behind [Delivery System Status](https://delivery-checks.prod.mozaws.net/html/index.html) and [Telescope for Taskcluster](https://telescope-demo.api.data.allizom.org/html/index.html)".

The benefit to code names is that changing the product name doesn't stop the world while you rename all the code references to the new name. The biggest downside to product names is discoverability - how do you get from the name everyone uses to the code? This is really important for commercial products, where confusion means lost sales. I'm not as sure with open-source products, where devs are used to following links and code names. I think it could be improved with a footer link like "Telescope for Taskcluster is powered by [Poucave](https://github.com/mozilla-services/poucave)", linking back to the project, in each instance.

**Comment by petemoore** [comment] 2021-08-25 14:48
I tend to agree. Also there are probably fewer software tools called poucave than telescope, so it hopefully makes it easier to find.

**Closed** 2021-09-15 13:04 UTC
Labels: taskcluster
